### ISSUE TITLE
Image issue

### ISSUE THREAD

**Issue by muruganklt** [kolkov/angular-editor#136]
Insert Image not working. I am trying to insert image but not happening any changes

**Comment by kolkov** [comment]
Where?

**Comment by muruganklt** [comment]
I am trying to insert image in an angular editor but the image did not insert and I have configured upload path correctly. 

htmlEditorConfig: AngularEditorConfig = {
    editable: true,
    spellcheck: true,
    height: '20rem',
    minHeight: '20rem',
    placeholder: 'description...',
    translate: 'no',
    uploadUrl: 'src/app/image', // if needed
    customClasses: [ // optional
      {
        name: "quote",
        class: "quote",
      },
      {
        name: 'redText',
        class: 'redText'
      },
      {
        name: "titleText",
        class: "titleText",
        tag: "h1",
      },
    ]
  };

**Comment by kolkov** [comment]
Provide you backend response please.

**Comment by muruganklt** [comment]
![Capture1](https://user-images.githubusercontent.com/51367333/63342386-f838d500-c368-11e9-8682-a86b93f78313.PNG)
![Capture](https://user-images.githubusercontent.com/51367333/63342388-f838d500-c368-11e9-8ece-a585a4f937f7.PNG)

**Comment by muruganklt** [comment]
![Capture](https://user-images.githubusercontent.com/51367333/63342716-cecc7900-c369-11e9-8fe3-baeb320498d6.PNG)

**Comment by Vikaton** [comment]
`uploadUrl` doesn't upload locally like that, it posts the image data to that URL endpoint on your server so you can save it through there.

**Comment by muruganklt** [comment]
![Capture1](https://user-images.githubusercontent.com/51367333/63403140-a3926a00-c3fb-11e9-89d0-55810ba954d7.PNG)
Can you please provide any example code because of your demo and example not working

**Comment by muruganklt** [comment]
now I am using another angular editor because of this editor not working correctly. Thanks

**Comment by hermscoder** [comment]
I will leave a comment here because I was looking for it for a long time but couldn't find a solution to my problem. My API is working wonderfully and returning the expected, but when I upload something nothing is added to the text editor. So I created an upload function instead, and according to the code, what was supposed to happen was:
 `this.upload(file).subscribe(() => this.watchUploadImage);`
but the method _watchUploadImage_ is never called, and because of this, my image was not being added to the text editor content.

So the only solution I could find was:
First I created a property on the controller using:
` @ViewChild() angularEditorComponent : AngularEditorComponent`
to reference the AngularEditorComponent on the screen.
And inside my upload function I did this:

`    upload: (file: File) => {
      this.fileUploadService.uploadFile(file).subscribe((response: any)=> {
     //adding the image tag by hand. it is bad, but it solves the problem
        this.angularEditorComponent?.writeValue(
          `<div><img src="` + response.imageUrl + `" ></div>`
        );
      });
      //returning this because the component expects a Observable<HttpEvent<UploadResponse>> return.
      return of<HttpEvent<UploadResponse>>();
    },`
